name: Bundle js

on:
  workflow_dispatch:
  push:
    branches: ["tech-counts-editor"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tech-counts-editor branch
        uses: actions/checkout@v3
        with:
          ref: tech-counts-editor

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build
        run: |
          npm install
          npm run build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
